# Generated by Django 2.1.5 on 2019-10-24 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='author name', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='body',
            field=models.TextField(default='This is the body of the article'),
        ),
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
