# Generated by Django 2.1.5 on 2019-10-25 06:59

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191024_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='the_slug', editable=False, populate_from='title', unique=True),
        ),
    ]
